status = [
  "Check (default)",
  "Check (full)",
  "Check (pbjson)",
  "Check (protoc)",
  "Clippy (default)",
  "Clippy (full)",
  "Clippy (pbjson)",
  "Package",
  "Rustdoc",
  "Rustfmt",
  "Test (default)",
  "Test (full)",
  "Test (pbjson)",
]
delete_merged_branches = true
timeout_sec = 600
