# SPDX-License-Identifier: Apache-2.0
status = [
  "Check (stable, full)",
  "Check (stable, pbjson)",
  "Check (stable, protoc)",
  "Check (1.64.0, full)",
  "Check (1.64.0, pbjson)",
  "Clippy (full)",
  "Clippy (pbjson)",
  "Conventional Commits",
  "Formatting",
  "Package",
  "Rustdoc",
  "Rustfmt",
  "SPDX License Header",
  "Test (full)",
  "Test (pbjson)"
]
delete-merged-branches = true
timeout-sec = 600
use-squash-merge = true
