# SPDX-License-Identifier: Apache-2.0

status = [
  "Check (default)",
  "Check (pbjson)",
  "Check (protoc)",
  "Check (serde)",
  "Clippy (default)",
  "Clippy (pbjson)",
  "Clippy (serde)",
  "License",
  "Rustdoc",
  "Rustfmt",
  "Test (default)",
  "Test (pbjson)",
  "Test (serde)",
]
delete-merged-branches = true
timeout-sec = 600
use-squash-merge = true
