status = [
  "Check (default)",
  "Check (pbjson)",
  "Check (semver,serde)",
  "Test (default)",
  "Test (pbjson)",
  "Test (semver,serde)",
  "Rustfmt",
  "Clippy (default)",
  "Clippy (pbjson)",
  "Clippy (semver,serde)",
  "Rustdoc",
  "Package",
]
delete_merged_branches = true
timeout_sec = 600
