# SPDX-License-Identifier: Apache-2.0

status = [
  "Check %",
  "Clippy %",
  "Conventional Commits",
  "License",
  "Rustdoc",
  "Rustfmt",
  "Test %",
]
delete-merged-branches = true
timeout-sec = 600
use-squash-merge = true
