# SPDX-License-Identifier: Apache-2.0
[package]
name = "substrait"
version = "0.9.0"
edition = "2021"
rust-version = "1.64"
description = "Cross-Language Serialization for Relational Algebra"
documentation = "https://docs.rs/substrait"
readme = "README.md"
homepage = "https://substrait.io"
repository = "https://github.com/substrait-io/substrait-rs"
license = "Apache-2.0"
keywords = ["substrait"]
build = "build.rs"
include = [
  "build.rs",
  "LICENSE",
  "src/**/*.rs",
  "src/extensions.in",
  "src/version.in",
  "src/version",
  "substrait/extensions/**/*.yaml",
  "substrait/LICENSE",
  "substrait/proto/**/*.proto",
  "substrait/README.md",
  "substrait/text/**/*.yaml",
]

[features]
default = []
extensions = ["dep:once_cell"]
full = ["extensions", "parse", "parser", "pbjson", "semver"]
parse = [
  "dep:hex",
  "dep:reqwest",
  "dep:thiserror",
  "dep:tracing",
  "dep:url",
  "extensions", # todo make this optional - the parser can just skip it
  "semver"
]
parser = ["dep:anyhow", "dep:clap", "dep:tracing-subscriber", "parse", "pbjson"]
pbjson = ["dep:pbjson", "dep:pbjson-build", "dep:pbjson-types"]
protoc = ["dep:protobuf-src"]
semver = ["dep:semver"]
serde = ["dep:prost-wkt", "dep:prost-wkt-build", "dep:prost-wkt-types"]

[[bin]]
name = "parser"
required-features = ["parser"]

[dependencies]
anyhow = { version = "1.0.70", optional = true }
clap = { version = "4.1.13", features = ["derive"], optional = true }
hex = { version = "0.4.3", optional = true }
once_cell = { version = "1.17.1", optional = true }
pbjson = { version = "0.5.1", optional = true }
pbjson-types = { version = "0.5.1", optional = true }
prost = "0.11.8"
prost-types = "0.11.8"
prost-wkt = { version = "0.4.1", optional = true }
prost-wkt-types = { version = "0.4.1", optional = true }
reqwest = { version = "0.11.16", features = ["blocking"], optional = true }
semver = { version = "1.0.17", optional = true }
serde = { version = "1.0.158", features = ["derive"] }
serde_json = "1.0.94"
serde_yaml = "0.9.19"
thiserror = { version = "1.0.40", optional = true }
tracing = { version = "0.1.37", optional = true }
tracing-subscriber = { version = "0.3.16", optional = true }
url = { version = "2.3.1", optional = true }

[build-dependencies]
git2 = { version = "0.17.1", default-features = false }
heck = "0.4"
pbjson-build = { version = "0.5", optional = true }
prettyplease = "0.2.4"
prost-build = { version = "0.11", default-features = false }
prost-types = "0.11"
prost-wkt-build = { version = "0.4", optional = true }
protobuf-src = { version = "1", optional = true }
schemars = "0.8"
semver = "1"
serde_yaml = "0.9"
syn = "2.0.11"
typify = "0.0.12"
walkdir = "2"

[dev-dependencies]
walkdir = "2.3.3"

[package.metadata.docs.rs]
features = ["full"]
rustdoc-args = ["--cfg", "docsrs"]
