# SPDX-License-Identifier: Apache-2.0

name: Docs

on:
  push:
  pull_request:

permissions:
  actions: write
  contents: read
  id-token: write
  pages: write

concurrency:
  group: ${{ github.ref }}

jobs:
  rustdoc:
    name: Rustdoc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-docs-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-docs-
            ${{ runner.os }}-cargo-
      - uses: dtolnay/rust-toolchain@nightly
      - uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: cargo rustdoc --lib --features full -- --cfg docsrs
      - run: chmod -c -R +rX "target/doc"
      - run: echo "<meta http-equiv=refresh content=0;url=substrait>" > target/doc/index.html
      - if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v1
        with:
          path: target/doc/

  deploy:
    name: Deploy
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: rustdoc
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/configure-pages@v3
      - uses: actions/deploy-pages@v2
        id: deployment
