# SPDX-License-Identifier: Apache-2.0

name: Pull Request

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  title:
    name: Title
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.pull_request.title, '[Merged by Bors] - ')"
    steps:
      - uses: actions/setup-node@v3
      - run: npm install @commitlint/config-conventional
      - id: commitlint
        run: echo "${{ github.event.pull_request.title }}" | npx commitlint --extends @commitlint/config-conventional
      - if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            const message = `Substrait follows the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/) for automate releases.
              The PR title is used as the merge commit message.
              
              Please update your PR title to match the specification.`

            // Get list of current comments
            const list_comments = github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            })
            const comments = await github.paginate(list_comments)

            // Check if this job already commented
            for (const comment of comments) {
              if (comment.body === message) {
                return // Already commented
              }
            }

            // Post the comment about Conventional Commits
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: message
            })
            core.setFailed('Invalid PR title')
