# SPDX-License-Identifier: Apache-2.0

name: Pull request

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  title:
    name: Title
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
      - run: npm install @commitlint/config-conventional
      - id: commitlint
        run: echo "${{ github.event.pull_request.title }}" | npx commitlint --extends @commitlint/config-conventional
      - if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            const body = `Substrait follows the [Conventional Commits specification](https://www.conventionalcommits.org/en/v1.0.0/) for automate releases.
              The PR title is used as the commit message when squash merging.
              
              Please update your PR title to match the specification.`

            const list_comments = github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
            });
            const comments = await github.paginate(list_comments)
            for (const comment of comments) {
              if (comment.body === body) {
                return // Already commented
              }
            }
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: 
            })
            core.setFailed('Invalid PR title')
