name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - uses: dtolnay/rust-toolchain@stable
      - uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: cargo install cargo-smart-release --debug --locked
      - run: cargo build
      - run: |
          cargo smart-release \
            --update-crates-index \
            --write-changelog \
            --no-publish \
            --verbose \
            --allow-dirty \
            substrait
