# SPDX-License-Identifier: Apache-2.0

name: Release

on:
  push:
    branches:
      - main

permissions:
  actions: write
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    concurrency: release
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-release-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-release-
            ${{ runner.os }}-cargo-
      - uses: dtolnay/rust-toolchain@stable
      - uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - run: cargo install cargo-smart-release --locked
      - run: cargo check --features full
      - run: cargo changelog --execute substrait
      - run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - env:
          GH_TOKEN: ${{ github.token }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: |
          cargo smart-release \
            --update-crates-index \
            --allow-fully-generated-changelogs \
            --execute \
            --no-changelog-preview \
            --allow-dirty \
            --verbose \
            substrait
